# From stage left to stage right
- name1: Joe
  name2: Bloggs
  buzzer: buzz.ogg
- name1: Penny
  name2: Farthing
  buzzer: buzz.ogg
- name1: Obi Wan
  name2: Kenobi
  buzzer: buzz.ogg
- name1: John
  name2: Smith
  buzzer: buzz.ogg
