# From stage left to stage right
- name1: Nadia
  name2: Odunayo
  buzzer: buzz.ogg
- name1: Kirsten
  name2: Hunter
  buzzer: buzz.ogg
- name1: Scott
  name2: Hanselman
  buzzer: buzz.ogg
- name1: Ruth
  name2: John
  buzzer: buzz.ogg
