dev:
  x_size: 640
  y_size: 480
  full_screen: false
dev_square:
  x_size: 512
  y_size: 384
  full_screen: false
dev_wide:
  x_size: 683
  y_size: 384
  full_screen: false
laptop_screen:
  x_size: 1366
  y_size: 768
  full_screen: true
square_screen:
  x_size: 1024
  y_size: 768
  full_screen: false
full_hd:
  x_size: 1920
  y_size: 1080
  full_screen: true